---
title: "density"
author: "zilani"
date: "16 October 2018"

output: 
    html_document:
      theme: flatly 
      highlight: tango
      toc: true
      toc_float: true
---

<style>
h3 {
  color: white;
  background-color: #44546a;
  text-indent: auto; 
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




**#########################################################################################**

# Density in random data 


```{r}

# creating two random data file, combind them 
# after than making the histogram in r

data1<-rnorm(1000, mean=25, sd=5)
data2<-rnorm(1000, mean=10, sd=2)

# combind two data file and ploting the histogram with the default bin size
data<-c(data1, data2)
hist(data)
hist(data,plot=FALSE)

# while the bin size 2, 10, 20, 30, 40 respectively
hist(data, probability=TRUE, main="#Bin of 2", breaks=2)
hist(data, probability=TRUE, main="#Bin of 10", breaks=10)
hist(data, probability=TRUE, main="#Bin of 20", breaks=20)
hist(data, probability=TRUE, main="#Bin of 30", breaks=30)
hist(data, probability=TRUE, main="#Bin of 40", breaks=40)

```

**#########################################################################################**

# Density curb random data 


```{r}
# using the density function we can get the curb

kde=density(data)
plot(kde)
```


**#########################################################################################**

# kernel Density(random data) 


```{r}
# set bandwidth 
h <- 1.5

# estimate density of x using different kernels
d1 <- density(data, bw=h, kernel="epanechnikov")
d2 <- density(data, bw=h, kernel="triangular")
d3 <- density(data, bw=h, kernel="gaussian")
d4 <- density(data, bw=h, kernel="biweight")

# Ouput estimated densities bean size=30
par(mfrow=c(2,2))
hist(data, breaks=30, freq=FALSE, col="lightgray", xlab="", ylab="", main="Epanechnikov")
lines(d1, lwd=2, col="red")

hist(data, breaks=30, freq=FALSE, col="lightgray", xlab="", ylab="", main="Triangular")
lines(d2, lwd=2, col="red")

hist(data, breaks=30, freq=FALSE, col="lightgray", xlab="", ylab="", main="Normal")
lines(d3, lwd=2, col="red")

hist(data, breaks=30, freq=FALSE, col="lightgray", xlab="", ylab="", main="Biweight")
lines(d4, lwd=2, col="red")
```



**#########################################################################################**

# kernel Density in various bandwidth 

```{r, warning=FALSE, message=FALSE, fig.width=8, fig.height=6}


# test different bandwiths
h <- c(0.3, 1.625, 3)

# using Gaussian kernel with different bandwiths to estimate density of y 
d1 <- density(data, bw = h[1], kernel = "gaussian")
d2 <- density(data, bw = h[2], kernel = "gaussian")
d3 <- density(data, bw = h[3], kernel = "gaussian")

# plot estimation results
hist(data, breaks=30, freq=FALSE, col="gray")

lines(d1$x, d1$y, col="red")

lines(d1, col="gold", lwd=3)
lines(d2$x, d2$y, lwd=2, col="blue3")
lines(d3$x, d3$y, lty=2, col="green4")
```



**#########################################################################################**

# cv in gaussian 


```{r}


# Use cross-validation to select bandwidth
h.bcv <- bw.bcv(data)

# Estimate density of x using Gaussian kernel and bandwidth selected by cross-validation method.
d.bcv <- density(data, bw=h.bcv, kernel="gaussian")

# Output bandwidth selected by each method 
h.bcv

## Plot estimation results
hist(data, breaks=30, freq=FALSE, col="gray")
lines(d.bcv, col="green4", lwd=2)
```


**#########################################################################################**

# Density in mtcar


```{r}
# ploting the kernal density of mpg in mtcars data
mtcars<-mtcars
d<-density(mtcars$mpg)
plot(d)

#ploting in red colour
plot(d, main="Kernal density", col="red")

# showing the bandwidth of the smoothness of the curb
# bw=bandwidth
# n=the number of equally spaced points at which the density is to be estimated.
dkernal<-density(mtcars$mpg, bw=2.5,n=50)
plot(dkernal)
```

**#########################################################################################**

# Density in various kernel 


```{r}
# set bandwidth 
h <- 2.5

# estimate density of x using different kernels
d1 <- density(mtcars$mpg, bw=h, kernel="epanechnikov")
d2 <- density(mtcars$mpg, bw=h, kernel="triangular")
d3 <- density(mtcars$mpg, bw=h, kernel="gaussian")
d4 <- density(mtcars$mpg, bw=h, kernel="biweight")

# Ouput estimated densities
par(mfrow=c(2,2))
hist(mtcars$mpg, breaks=20, freq=FALSE, col="lightgray", xlab="", ylab="", main="Epanechnikov")
lines(d1, lwd=2, col="red")

hist(mtcars$mpg, breaks=20, freq=FALSE, col="lightgray", xlab="", ylab="", main="Triangular")
lines(d2, lwd=2, col="red")

hist(mtcars$mpg, breaks=20, freq=FALSE, col="lightgray", xlab="", ylab="", main="Normal")
lines(d3, lwd=2, col="red")

hist(mtcars$mpg, breaks=20, freq=FALSE, col="lightgray", xlab="", ylab="", main="Biweight")
lines(d4, lwd=2, col="red")
```


**#########################################################################################**

# Density in gaussian(mtcar) 


```{r, warning=FALSE, message=FALSE, fig.width=8, fig.height=6}


# test different bandwiths
h <- c(0.3, 2.5, 4)

# using Gaussian kernel with different bandwiths to estimate density of y 
d1 <- density(mtcars$mpg, bw = h[1], kernel = "gaussian")
d2 <- density(mtcars$mpg, bw = h[2], kernel = "gaussian")
d3 <- density(mtcars$mpg, bw = h[3], kernel = "gaussian")

# plot estimation results
hist(mtcars$mpg, breaks=20, freq=FALSE, col="gray")

lines(d1$x, d1$y, col="red")

lines(d1, col="gold", lwd=3)
lines(d2$x, d2$y, lwd=2, col="blue3")
lines(d3$x, d3$y, lty=2, col="green4")
```


**#########################################################################################**

# Density cv in mtcar 

```{r}

# Use cross-validation to select bandwidth
h.bcv <- bw.bcv(mtcars$mpg)

# Estimate density of x using Gaussian kernel and bandwidth selected by cross-validation method.
d.bcv <- density(mtcars$mpg, bw=h.bcv, kernel="gaussian")

# Output bandwidth selected by each method 
h.bcv

## Plot estimation results
hist(mtcars$mpg, breaks=30, freq=FALSE, col="gray")
lines(d.bcv, col="green4", lwd=2)
```



